
# Week 01 Assignment  
## Data Quality, Evaluation, Scaling, and Encoding

**Student name: MD.Shoyeb**   

This is a small assignment that connects topics from Module 1, 2, and 3.  
You must complete it in this Colab notebook.

You will need to use concepts that appeared in the videos:
- Module 1 and 2: basic descriptive statistics, proportions, confusion matrix, accuracy, precision, recall
- Module 3: standardization, min max scaling, nominal vs ordinal, one hot encoding, ordinal encoding, Euclidean and Manhattan distance

Please do not use any extra libraries beyond `pandas`, `numpy`.


---
## 0. Setup and Dataset

We will use a dataset that should have columns given below:

- `user_id`  
- `age`  
- `monthly_income` (numeric)  
- `daily_screen_time_min` (numeric)  
- `daily_app_opens` (numeric)  
- `true_label` and `pred_label` for a binary classification task (0 or 1)  
- `satisfaction_level` (for example: `Low`, `Medium`, `High`)  
- `city_type` (for example: `Urban`, `Suburban`, `Rural`)

In [26]:
# Cell 1: Imports
import pandas as pd
import numpy as np

In [27]:
# Cell 2: Load the dataset (Already done for you)
df = pd.read_csv("https://drive.google.com/uc?export=download&id=1OmDDCh4MD1TtvAemnwVDyz5zwCIXJ220")

# Show first few rows
df.head()

,user_id,age,monthly_income,daily_screen_time_min,daily_app_opens,true_label,pred_label,satisfaction_level,city_type
0,1,43,3734.19,109,48,0,0,Medium,Suburban
1,2,49,2594.19,194,7,0,0,Low,Urban
2,3,19,3550.47,146,36,1,0,High,Rural
3,4,19,3821.18,287,14,1,0,High,Suburban
4,5,63,1750.84,66,46,0,0,Medium,Suburban


### 0.1 Check your dataset

1. Confirm that the dataset loaded correctly.  
2. Check that you have at least these columns:  
   - numeric: `age`, `monthly_income`, `daily_screen_time_min`, `daily_app_opens`  
   - labels: `true_label`, `pred_label`  
   - categorical: `satisfaction_level`, `city_type`


---
## Part A - Module 1 and 2 Review

In this part you will do simple descriptive statistics and basic classification evaluation.


### Q1. Descriptive statistics on a numeric feature

Choose one numeric column, for example `daily_screen_time_min`.

In [28]:
# Q1.1: Choose your numeric column here [We already write this ans]
num_col = "daily_screen_time_min"

df[num_col].describe()

count    100.000000
mean     181.890000
std       68.886951
min       60.000000
25%      122.000000
50%      178.000000
75%      243.750000
max      299.000000
Name: daily_screen_time_min, dtype: float64


> **Q1.2 Short answer: [Marks: 05]**  
> Look at the count, mean, min, max, and standard deviation for your chosen column.  
> In 2 to 3 sentences, comment on what you see.  
> For example, does the max look very far from the mean, or does it look quite close?

Write your answer here:

>  in this data mean tell us daily average screen time.

>  median show the middle screen time.

>  std tell us how spread out screen time.


### Q2. Proportion of positive class

Use the `true_label` column, where 1 means "positive" and 0 means "negative".

In [29]:
# Q2.1: Compute proportion of positive class [We already write this ans]
label_col = "true_label"

positive_count = (df[label_col] == 1).sum()
total_count = df.shape[0]
positive_proportion = positive_count / total_count

print("Positive count:", positive_count)
print("Total samples:", total_count)
print("Proportion of positive class:", positive_proportion)

Positive count: 52
Total samples: 100
Proportion of positive class: 0.52


> **Q2.2 Short answer: [5 marks]**  
> In 1 to 2 sentences, explain what this proportion tells you about your dataset.  
> For example, is the dataset balanced between 0 and 1, or is one class much more common?

Write your answer here:

>  this dataset represent the probabilities and scaling.
>  positive score with total of record.
>  feature scaling and standard deviation.


### Q3. Confusion matrix and basic metrics

For this question, use:
- `true_label` as the actual label  
- `pred_label` as the model prediction

In [30]:
# Q3.1: Manually compute TP, TN, FP, FN [We already write this ans]
true_col = "true_label"
pred_col = "pred_label"

tp = ((df[true_col] == 1) & (df[pred_col] == 1)).sum()
tn = ((df[true_col] == 0) & (df[pred_col] == 0)).sum()
fp = ((df[true_col] == 0) & (df[pred_col] == 1)).sum()
fn = ((df[true_col] == 1) & (df[pred_col] == 0)).sum()

print("TP:", tp)
print("TN:", tn)
print("FP:", fp)
print("FN:", fn)

TP: 28
TN: 27
FP: 21
FN: 24

In [31]:
# Q3.2: Compute accuracy, precision, recall [We already write this ans]
accuracy = (tp + tn) / (tp + tn + fp + fn) if (tp + tn + fp + fn) > 0 else 0

precision = tp / (tp + fp) if (tp + fp) > 0 else 0
recall = tp / (tp + fn) if (tp + fn) > 0 else 0

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)

Accuracy: 0.55
Precision: 0.5714285714285714
Recall: 0.5384615384615384


> **Q3.3 Short answer: [10 marks]**  
> In 3 to 4 sentences, briefly comment on the model using these three metrics.  
> For example, is the model catching most positives (high recall) or being careful when it predicts positive (high precision)?

Write your answer here:

>  this data represent for understanding sensitivity specificity and predictive value.

>  this model show 55% of accurachy and
>  positive predictive value or precision


---
## Part B - Module 3: Scaling and Encoding

Now we will pick a few features and apply scaling and encoding.


### Q4. Standardization and Min max scaling

Use one numeric column, `monthly_income`.

In [32]:
# Q4.1: Choose the numeric column [2 marks]

num_col = "monthly_income"

In [33]:
# Q4.2: Standardization with z-score [10 marks]

std = df[num_col].std()
print("Standard Deviation:", std)
Z_score = (df[num_col] - df[num_col].mean()) / df[num_col].std()
print("Z-score:", Z_score)

Standard Deviation: 898.1246929878644
Z-score: 0     0.944685
1    -0.324626
2     0.740126
3     1.041542
4    -1.263639
        ...
95    1.213813
96    0.978734
97   -0.611613
98    0.135599
99   -0.768084
Name: monthly_income, Length: 100, dtype: float64

In [34]:
# Q4.3: Min max scaling implementation [10 marks]

min_val = df[num_col].min()
max_val = df[num_col].max()

print("Min:", min_val)
print("Max:", max_val)

Min: 1000.0
Max: 5049.4


> **Q4.4 Short answer: [3 marks]**  
> Compare the standardized and min max scaled columns in 2 to 3 sentences.  
> Mention what kind of range each one uses and how the numbers look.

Write your answer here:

>  standard deviation use for make feature comparable by ensuring that each each feature has mean and standard deviation.

>  Z - score normalize part of standard scaling, which transform all feature have mean 0 and and standard deviation 1.
>


### Q5. One hot and ordinal encoding

We will use:
- `city_type` as a nominal feature  
- `satisfaction_level` as an ordinal feature with order `Low` < `Medium` < `High`

In [35]:
# Q5.1: One hot encoding for city_type using pandas [10 marks]

one_hot_encoded = pd.get_dummies(df["city_type"], prefix="convert", dtype=int)
df = pd.concat([df, one_hot_encoded], axis=1)
df_encoded= df.drop("city_type", axis=1)
print(df_encoded)

    user_id  age  monthly_income  daily_screen_time_min  daily_app_opens  \
0         1   43         3734.19                    109               48
1         2   49         2594.19                    194                7
2         3   19         3550.47                    146               36
3         4   19         3821.18                    287               14
4         5   63         1750.84                     66               46
..      ...  ...             ...                    ...              ...
95       96   20         3975.90                    259               15
96       97   52         3764.77                    295               16
97       98   35         2336.44                    108               46
98       99   18         3007.53                    202               42
99      100   57         2195.91                     75               18

    true_label  pred_label satisfaction_level  convert_Rural  \
0            0           0             Medium              0
1            0           0                Low              0
2            1           0               High              1
3            1           0               High              0
4            0           0             Medium              0
..         ...         ...                ...            ...
95           0           1             Medium              0
96           1           0                Low              0
97           0           1               High              1
98           1           1               High              0
99           1           0             Medium              0

    convert_Suburban  convert_Urban
0                  1              0
1                  0              1
2                  0              0
3                  1              0
4                  1              0
..               ...            ...
95                 0              1
96                 0              1
97                 0              0
98                 0              1
99                 1              0

[100 rows x 11 columns]

In [36]:
# Q5.2: Attach one hot encoded columns to df [5 marks]
attach_column = pd.get_dummies(df["satisfaction_level"], prefix="convert", dtype=int)
df = pd.concat([df, attach_column], axis=1)
df

,user_id,age,monthly_income,daily_screen_time_min,daily_app_opens,true_label,pred_label,satisfaction_level,city_type,convert_Rural,convert_Suburban,convert_Urban,convert_High,convert_Low,convert_Medium
0,1,43,3734.19,109,48,0,0,Medium,Suburban,0,1,0,0,0,1
1,2,49,2594.19,194,7,0,0,Low,Urban,0,0,1,0,1,0
2,3,19,3550.47,146,36,1,0,High,Rural,1,0,0,1,0,0
3,4,19,3821.18,287,14,1,0,High,Suburban,0,1,0,1,0,0
4,5,63,1750.84,66,46,0,0,Medium,Suburban,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,20,3975.90,259,15,0,1,Medium,Urban,0,0,1,0,0,1
96,97,52,3764.77,295,16,1,0,Low,Urban,0,0,1,0,1,0
97,98,35,2336.44,108,46,0,1,High,Rural,1,0,0,1,0,0
98,99,18,3007.53,202,42,1,1,High,Urban,0,0,1,1,0,0
99,100,57,2195.91,75,18,1,0,Medium,Suburban,0,1,0,0,0,1

In [37]:
# Q5.3: Ordinal encoding for satisfaction_level [10 marks]

order = {"Low": 1, "Medium": 2, "High": 3}
df["satisfaction_level"] = df["satisfaction_level"].map(order).astype(int)
df

,user_id,age,monthly_income,daily_screen_time_min,daily_app_opens,true_label,pred_label,satisfaction_level,city_type,convert_Rural,convert_Suburban,convert_Urban,convert_High,convert_Low,convert_Medium
0,1,43,3734.19,109,48,0,0,2,Suburban,0,1,0,0,0,1
1,2,49,2594.19,194,7,0,0,1,Urban,0,0,1,0,1,0
2,3,19,3550.47,146,36,1,0,3,Rural,1,0,0,1,0,0
3,4,19,3821.18,287,14,1,0,3,Suburban,0,1,0,1,0,0
4,5,63,1750.84,66,46,0,0,2,Suburban,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,20,3975.90,259,15,0,1,2,Urban,0,0,1,0,0,1
96,97,52,3764.77,295,16,1,0,1,Urban,0,0,1,0,1,0
97,98,35,2336.44,108,46,0,1,3,Rural,1,0,0,1,0,0
98,99,18,3007.53,202,42,1,1,3,Urban,0,0,1,1,0,0
99,100,57,2195.91,75,18,1,0,2,Suburban,0,1,0,0,0,1


> **Q5.4 Short answer: [5 marks]**  
> In 2 to 3 sentences, explain why one hot encoding is suitable for `city_type`  
> and why ordinal encoding is suitable for `satisfaction_level`.

Write your answer here:

>  one hot encoding best for nominal categorical data that are names/label.
>  Because these categories don’t have any order.
So assigning numbers (1, 2, 3) would mislead the model.

>  Ordinal categorical data natural order present,Categories that have a ranking


---
## Part C - Module 3: Distances between users

For this small part we will work with vectors based on scaled numeric features.


### Q6. Euclidean and Manhattan distance

Build 2D vectors for user 0 and user 1 using:
- `income_std`  
- `daily_app_opens` (or its min max scaled version if you prefer)

In [38]:
# Q6.1: Build 2D vectors for first two users [We already write this ans]
vec_cols = ["monthly_income", "daily_app_opens"]

v1 = df.loc[0, vec_cols].values
v2 = df.loc[1, vec_cols].values

print("v1:", v1)
print("v2:", v2)

v1: [np.float64(3734.19) np.int64(48)]
v2: [np.float64(2594.19) np.int64(7)]

In [39]:
# Q6.2: Euclidean distance computation [5 marks]
eudi = np.linalg.norm(v1 - v2)
print("Euclidean distance:", eudi)

Euclidean distance: 1140.7370424422975

In [40]:
# Q6.3: Manhattan distance computation [5 marks]
mandi = np.sum(np.abs(v1 - v2))
print("Manhattan distance:", mandi)

Manhattan distance: 1181.0


> **Q6.4 Short answer: [5 marks]**  
> Which one is larger in your result, Euclidean or Manhattan distance  
> and why does that usually happen based on their formulas?

Write your answer here:

>  Manhattan distance is larger than Euclidean distance.
>  Manhattan distance happen for the formula like you must fllow roads with round up right.
>  Euclidean distance take shortest path.


---
## Final Reflection [10 marks]

> In 4 to 6 sentences, describe how the three modules connect in this assignment.  
> Mention:
> - One idea from Module 1 or 2 that you used  
> - One idea from Module 3 that you used  
> - How these ideas together help you understand a dataset more deeply

Write your reflection here:

>  from module 1 i used descriptive statistics like Mean, Median, Mode and probabilities.
>  from module 2 nominal vs ordinal encoding and scaling.
>  from Module 3 i used standardization Z-Score and min max scaling.
>  both of the ideas help me for data analysis and data binding for machine learning.


## End of Assignment

Before submitting:
- Run all cells from top to bottom.  
- Check that all answer sections are filled.  
- Instruction video অনুযায়ী আমাদের দেয়া Colab ফাইলটি থেকে প্রথম একটি Save copy in drive করে নিবা। এরপর Google colab এর মধ্যে কোডগুলো করবে এবং সেই ফাইলটি ‘Anyone with the link’ & ‘View’ Access দিয়ে ফাইলটির Shareble Link টি সাবমিট করবে।